import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/utilities/SessionWrapper";
import { ThemeProvider } from "@/utilities/context/ThemeContext";
import MainNavbar from "@/components/Navbar/MainNavbar";
import AuthCheck from "@/components/AuthCheck";
import LoginForm from "@/components/LoginForm";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SessionWrapper>
          <ThemeProvider>
            <AuthCheck 
              fallback={<LoginForm />}
            >
              <MainNavbar />
              {children}
            </AuthCheck>
          </ThemeProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}